#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Defaults
DEFAULT_PORT=4020
DEFAULT_INSTALL_DIR="$HOME/.bridge-agent"
REPO_URL="https://github.com/GabrielOlvH/bridge.git"
SERVICE_NAME="bridge-agent"

echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════╗"
echo "║       ${BOLD}Bridge Agent Installer${NC}${CYAN}              ║"
echo "║       Terminal Management Server          ║"
echo "╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"

    local missing=()

    if ! command -v git &> /dev/null; then
        missing+=("git")
    fi

    if ! command -v node &> /dev/null; then
        missing+=("node")
    else
        NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
        if [ "$NODE_VERSION" -lt 18 ]; then
            echo -e "${RED}Error: Node.js >= 18 required (found v$NODE_VERSION)${NC}"
            exit 1
        fi
    fi

    if ! command -v npm &> /dev/null; then
        missing+=("npm")
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${RED}Error: Missing required tools: ${missing[*]}${NC}"
        echo "Please install them and try again."
        exit 1
    fi

    # Check for build tools (needed for node-pty)
    if ! command -v gcc &> /dev/null || ! command -v make &> /dev/null; then
        echo -e "${YELLOW}Warning: Build tools (gcc, make) may be needed for node-pty${NC}"
        echo "Install with: sudo apt install build-essential"
    fi

    echo -e "${GREEN}✓ All prerequisites met${NC}"
}

# Prompt with default
prompt() {
    local var_name=$1
    local prompt_text=$2
    local default=$3
    local is_secret=${4:-false}

    if [ "$is_secret" = true ]; then
        echo -ne "${CYAN}$prompt_text${NC}"
        read -s value
        echo
    else
        echo -ne "${CYAN}$prompt_text${NC}"
        read value
    fi

    if [ -z "$value" ]; then
        eval "$var_name='$default'"
    else
        eval "$var_name='$value'"
    fi
}

# Wizard
run_wizard() {
    echo -e "\n${BOLD}Configuration Wizard${NC}\n"

    # Install directory
    prompt INSTALL_DIR "Install directory [${DEFAULT_INSTALL_DIR}]: " "$DEFAULT_INSTALL_DIR"

    # Port
    prompt PORT "Agent port [${DEFAULT_PORT}]: " "$DEFAULT_PORT"

    # Host label
    DEFAULT_HOST=$(hostname)
    prompt HOST_LABEL "Host label (shown in app) [${DEFAULT_HOST}]: " "$DEFAULT_HOST"

    # Auth token
    echo -e "\n${YELLOW}Authentication token protects your agent from unauthorized access.${NC}"
    prompt AUTH_TOKEN "Auth token (leave empty for none): " "" false

    # Tmux socket (advanced)
    echo -e "\n${YELLOW}Advanced: Leave empty for default tmux socket${NC}"
    prompt TMUX_SOCKET "Tmux socket path [default]: " ""

    # Confirm
    echo -e "\n${BOLD}Configuration Summary:${NC}"
    echo -e "  Install directory: ${GREEN}$INSTALL_DIR${NC}"
    echo -e "  Port:              ${GREEN}$PORT${NC}"
    echo -e "  Host label:        ${GREEN}$HOST_LABEL${NC}"
    echo -e "  Auth token:        ${GREEN}${AUTH_TOKEN:-(none)}${NC}"
    echo -e "  Tmux socket:       ${GREEN}${TMUX_SOCKET:-(default)}${NC}"

    echo
    prompt CONFIRM "Proceed with installation? [Y/n]: " "Y"
    if [[ ! "$CONFIRM" =~ ^[Yy]?$ ]]; then
        echo -e "${RED}Installation cancelled${NC}"
        exit 0
    fi
}

# Install
install() {
    echo -e "\n${BLUE}Installing Bridge Agent...${NC}\n"

    # Clone or update repo
    if [ -d "$INSTALL_DIR" ]; then
        echo -e "${YELLOW}Existing installation found, updating...${NC}"
        cd "$INSTALL_DIR"
        git pull origin main || git pull origin master
    else
        echo "Cloning repository..."
        git clone "$REPO_URL" "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi

    # Install dependencies
    echo "Installing dependencies..."
    cd agent
    npm install

    # Create .env file
    echo "Creating configuration..."
    cat > .env << EOF
# Bridge Agent Configuration
# Generated by installer on $(date)

BRIDGE_INSTALL_DIR=$INSTALL_DIR
TMUX_AGENT_PORT=$PORT
TMUX_AGENT_HOST=$HOST_LABEL
TMUX_AGENT_TOKEN=$AUTH_TOKEN
TMUX_AGENT_SOCKET=$TMUX_SOCKET
TMUX_AGENT_USAGE_POLL_MS=60000
TMUX_AGENT_TOKEN_POLL_MS=180000
EOF

    echo -e "${GREEN}✓ Configuration saved${NC}"
}

# Setup systemd
setup_systemd() {
    echo -e "\n${BLUE}Setting up systemd services...${NC}"

    # Create user systemd directory
    mkdir -p "$HOME/.config/systemd/user"

    # Main service
    cat > "$HOME/.config/systemd/user/$SERVICE_NAME.service" << EOF
[Unit]
Description=Bridge Agent - Terminal Management Server
Documentation=https://github.com/GabrielOlvH/bridge
After=network.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR/agent
ExecStart=$(which node) $INSTALL_DIR/agent/node_modules/.bin/tsx $INSTALL_DIR/agent/index.ts
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bridge-agent
EnvironmentFile=$INSTALL_DIR/agent/.env

[Install]
WantedBy=default.target
EOF

    # Enable lingering (allows user services to run without login)
    if command -v loginctl &> /dev/null; then
        loginctl enable-linger "$USER" 2>/dev/null || true
    fi

    # Reload and enable
    systemctl --user daemon-reload
    systemctl --user enable "$SERVICE_NAME.service"
    systemctl --user start "$SERVICE_NAME.service"

    echo -e "${GREEN}✓ Systemd service configured and started${NC}"
}

# Print success
print_success() {
    echo -e "\n${GREEN}"
    echo "╔═══════════════════════════════════════════╗"
    echo "║         Installation Complete!            ║"
    echo "╚═══════════════════════════════════════════╝"
    echo -e "${NC}"

    echo -e "Bridge Agent is now running on port ${BOLD}$PORT${NC}"
    echo
    echo -e "${BOLD}Useful commands:${NC}"
    echo -e "  ${CYAN}View status:${NC}    systemctl --user status $SERVICE_NAME"
    echo -e "  ${CYAN}View logs:${NC}      journalctl --user -u $SERVICE_NAME -f"
    echo -e "  ${CYAN}Restart:${NC}        systemctl --user restart $SERVICE_NAME"
    echo -e "  ${CYAN}Stop:${NC}           systemctl --user stop $SERVICE_NAME"
    echo -e "  ${CYAN}Edit config:${NC}    nano $INSTALL_DIR/agent/.env"
    echo
    echo -e "${BOLD}Add to Bridge app:${NC}"
    echo -e "  URL: ${GREEN}http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'your-ip'):$PORT${NC}"
    if [ -n "$AUTH_TOKEN" ]; then
        echo -e "  Token: ${GREEN}$AUTH_TOKEN${NC}"
    fi
    echo
    echo -e "${YELLOW}Updates can be triggered from the Bridge app${NC}"
}

# Main
main() {
    check_prerequisites
    run_wizard
    install
    setup_systemd
    print_success
}

main "$@"
